---
title: 'The Billboard Equation: Midpoint Deliverable'
author: "Adam Bi, Jueqi Liu, Monica Hong, Nancy Han, Sonali Chandra"
date: "May 24, 2019"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
source("summaryInformation.R")
source("tempoVersusPopularity.R")

```  

# The Billboard Equation
_________________

## Project Rundown 



## Summary Information


```{r echo = FALSE}
summary_information <- get_summary_info(filtered_info)

```

## Key-Mode Pairings Summary Table
```{r echo = FALSE}
# Apply function to data to get the frequeuncy of key-mode pairings
key_mode_freq <- get_grouped_info(filtered_info)

```


## Key-Mode Pairings vs. Popularity Graph
```{r echo = FALSE}

```

## Tempo vs. Popularity


```{r echo = FALSE}
# Apply function to data
filtered_info$tempo_category <- cat_tempo(filtered_info)

# Apply function to data
group_tempo <- get_tempo_info(filtered_info)

# Construct a plot to present the summarized data
ggplot(group_tempo, aes(x = tempo_category, y = avg_popularity, group = 1)) +
  geom_line() +
  geom_point()
```


## Artists vs. Average Popularity
```{r echo = FALSE}

```

